### ISSUE TITLE
AUTOPILOT-004A: implement additive verifier-ledger migration

### ISSUE THREAD

**Issue by MsElysia** [MsElysia/Elysia#16]
## Parent
#8 AUTOPILOT-004; implementation lane PR #15; control plane #11.

## Objective
Implement only the idempotent additive SQLite schema migration required by the verifier lifecycle. Extend the existing `elysia_collective_seed/autopilot/task_ledger.py` ledger; do not create a second ledger.

## Required columns
- `produced_by TEXT`
- `completion_packet_id TEXT`
- `completion_evidence_json TEXT`
- `verification_claimed_by TEXT`
- `verification_lease_expires_at TEXT`
- `verification_rejections INTEGER NOT NULL DEFAULT 0`

## Acceptance
1. Existing pre-verifier ledger opens without drop/recreate.
2. Existing task payload/status/attempt and event history are preserved byte-for-semantics.
3. All six columns are added when absent.
4. Reopening is idempotent and does not duplicate columns or synthesize/destructively rewrite history.
5. Existing migration regression tests in PR #15 pass on the exact implementation head.
6. No provider/model invocation, Guardian runtime wiring, merge/deploy/external posting, credentials/private-chat access, private-data expansion, or authority expansion.

## Implementation constraint
Use bounded schema introspection such as `PRAGMA table_info(tasks)` and additive `ALTER TABLE ... ADD COLUMN` for missing columns. Preserve the existing task/event tables and execution lease fields. This task does not implement submit/claim/accept/reject/reap verification operations; those remain the next bounded slice after migration is green.

## Evidence / handoff
Completion must record exact commit SHA, exact test command/result, files changed, and any schema incompatibility. Keep PR #15 draft and unmerged.
